// <auto-generated />
namespace Saned.Jazan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterAllStored : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterAllStored));
        
        string IMigrationMetadata.Id
        {
            get { return "201705211149483_AlterAllStored"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
