// <auto-generated />
namespace Saned.Jazan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CulturalCompetitionQuestionCascadeDeletetrue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CulturalCompetitionQuestionCascadeDeletetrue));
        
        string IMigrationMetadata.Id
        {
            get { return "201705100908232_CulturalCompetitionQuestion-Cascade-Delete-true"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
