// <auto-generated />
namespace Saned.Jazan.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterAdvertisement_SelectPaging : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterAdvertisement_SelectPaging));
        
        string IMigrationMetadata.Id
        {
            get { return "201703201558114_alterAdvertisement_SelectPaging"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
